img_dir: "/home/dataset/imageNet/val/images"
# img_dir: "../demo_imgs"
# Ground truth file
gt_file: "../class_and_ground_truth/val.txt"
cls_file: "../class_and_ground_truth/imagenet_classes.txt"
# Sample_num: 128 from imageNet dataset
split: 10000
warmup_iter : 128
